---
# Development environment override
services:
  php:
    image: ${IMAGES_PREFIX:-}app-php-dev
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro
      - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
    environment:
      CADDY_SERVER_EXTRA_DIRECTIVES: "${CADDY_SERVER_EXTRA_DIRECTIVES:-}"
      FRANKENPHP_WORKER_CONFIG: watch
      FRANKENPHP_SITE_CONFIG: hot_reload
      MERCURE_EXTRA_DIRECTIVES: demo
      XDEBUG_MODE: "${XDEBUG_MODE:-develop}"
      APP_ENV: "${APP_ENV:-dev}"
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true

  worker:
    image: ${IMAGES_PREFIX:-}app-php-dev
    restart: unless-stopped
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-17}&charset=${POSTGRES_CHARSET:-utf8}
      APP_ENV: "${APP_ENV:-dev}"
    command: ["php", "bin/console", "messenger:consume", "async", "scheduler_fetch", "--time-limit=3600", "--memory-limit=128M", "-vv"]
    depends_on:
      - php


###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
