<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260407182412 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user_article_bookmark table for save-for-later feature';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_article_bookmark (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, article_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F29F24ABA76ED395 ON user_article_bookmark (user_id)');
        $this->addSql('CREATE INDEX IDX_F29F24AB7294869C ON user_article_bookmark (article_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_article_bookmark ON user_article_bookmark (user_id, article_id)');
        $this->addSql('ALTER TABLE user_article_bookmark ADD CONSTRAINT FK_F29F24ABA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_article_bookmark ADD CONSTRAINT FK_F29F24AB7294869C FOREIGN KEY (article_id) REFERENCES article (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_article_bookmark DROP CONSTRAINT FK_F29F24ABA76ED395');
        $this->addSql('ALTER TABLE user_article_bookmark DROP CONSTRAINT FK_F29F24AB7294869C');
        $this->addSql('DROP TABLE user_article_bookmark');
    }
}
