<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260404182201 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE digest_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, schedule VARCHAR(100) NOT NULL, categories JSON NOT NULL, article_limit SMALLINT NOT NULL, enabled BOOLEAN NOT NULL, last_run_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6B059BA7A76ED395 ON digest_config (user_id)');
        $this->addSql('CREATE TABLE digest_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, article_count SMALLINT NOT NULL, content TEXT NOT NULL, delivery_success BOOLEAN NOT NULL, transport VARCHAR(100) DEFAULT NULL, digest_config_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA12A62058A929E0 ON digest_log (digest_config_id)');
        $this->addSql('ALTER TABLE digest_config ADD CONSTRAINT FK_6B059BA7A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE digest_log ADD CONSTRAINT FK_AA12A62058A929E0 FOREIGN KEY (digest_config_id) REFERENCES digest_config (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE digest_config DROP CONSTRAINT FK_6B059BA7A76ED395');
        $this->addSql('ALTER TABLE digest_log DROP CONSTRAINT FK_AA12A62058A929E0');
        $this->addSql('DROP TABLE digest_config');
        $this->addSql('DROP TABLE digest_log');
    }
}
