<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260404153031 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(512) NOT NULL, url VARCHAR(2048) NOT NULL, content_raw TEXT DEFAULT NULL, content_text TEXT DEFAULT NULL, summary VARCHAR(1000) DEFAULT NULL, fingerprint VARCHAR(64) DEFAULT NULL, score DOUBLE PRECISION DEFAULT NULL, enrichment_method VARCHAR(20) DEFAULT NULL, ai_model_used VARCHAR(100) DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fetched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source_id INT NOT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23A0E66F47645AE ON article (url)');
        $this->addSql('CREATE INDEX IDX_23A0E66953C1C61 ON article (source_id)');
        $this->addSql('CREATE INDEX IDX_23A0E6612469DE2 ON article (category_id)');
        $this->addSql('CREATE INDEX idx_article_fingerprint ON article (fingerprint)');
        $this->addSql('CREATE INDEX idx_article_published_at ON article (published_at)');
        $this->addSql('CREATE INDEX idx_article_url ON article (url)');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, weight SMALLINT NOT NULL, color VARCHAR(7) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C1989D9B62 ON category (slug)');
        $this->addSql('CREATE TABLE source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, feed_url VARCHAR(2048) NOT NULL, site_url VARCHAR(2048) DEFAULT NULL, enabled BOOLEAN NOT NULL, error_count SMALLINT NOT NULL, last_error_message TEXT DEFAULT NULL, health_status VARCHAR(20) NOT NULL, last_fetched_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5F8A7F736FAD93B ON source (feed_url)');
        $this->addSql('CREATE INDEX IDX_5F8A7F7312469DE2 ON source (category_id)');
        $this->addSql('CREATE TABLE user_article_read (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, article_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A8D9BA64A76ED395 ON user_article_read (user_id)');
        $this->addSql('CREATE INDEX IDX_A8D9BA647294869C ON user_article_read (article_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_article ON user_article_read (user_id, article_id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E6612469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F7312469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_article_read ADD CONSTRAINT FK_A8D9BA64A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_article_read ADD CONSTRAINT FK_A8D9BA647294869C FOREIGN KEY (article_id) REFERENCES article (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE article DROP CONSTRAINT FK_23A0E66953C1C61');
        $this->addSql('ALTER TABLE article DROP CONSTRAINT FK_23A0E6612469DE2');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F7312469DE2');
        $this->addSql('ALTER TABLE user_article_read DROP CONSTRAINT FK_A8D9BA64A76ED395');
        $this->addSql('ALTER TABLE user_article_read DROP CONSTRAINT FK_A8D9BA647294869C');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE source');
        $this->addSql('DROP TABLE user_article_read');
    }
}
