<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260410111727 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "key" VARCHAR(100) NOT NULL, value VARCHAR(500) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F74B898F48571EB ON setting ("key")');
        $this->addSql('ALTER TABLE source ALTER success_count DROP DEFAULT');
        $this->addSql('ALTER TABLE source ALTER failure_count DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE setting');
        $this->addSql('ALTER TABLE source ALTER success_count SET DEFAULT 0');
        $this->addSql('ALTER TABLE source ALTER failure_count SET DEFAULT 0');
    }
}
